import { chromium } from 'playwright'
const b = await chromium.launch({ headless: true })
const p = await (await b.newContext({ viewport: { width: 1536, height: 743 }, deviceScaleFactor: 1.25 })).newPage()
p.on('requestfailed', (r) => console.log('FAILED', r.url(), r.failure()?.errorText))
p.on('response', (r) => { if (r.status() >= 400) console.log('HTTP', r.status(), r.url()) })
p.on('console', (m) => { if (m.type() === 'error') console.log('CONSOLE-ERR', JSON.stringify(m.text()), m.location()) })
await p.goto('http://localhost:5177/', { waitUntil: 'networkidle' })
await p.waitForTimeout(1000)
await p.getByRole('link', { name: 'About', exact: true }).click()
await p.waitForTimeout(800)
await p.getByRole('link', { name: 'Quarterfold Printabilities home' }).click()
await p.waitForTimeout(1200)
console.log('direct /favicon.ico status:', (await p.request.get('http://localhost:5177/favicon.ico')).status())
await b.close()
